version: '3.8'

services:
  blockchainsim:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: blockchainsim-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/users"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blockchainsim-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: blockchainsim-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - blockchainsim
    restart: unless-stopped
    networks:
      - blockchainsim-network
    profiles:
      - production

networks:
  blockchainsim-network:
    driver: bridge

# Optional volumes for persistence (if needed in future)
volumes:
  blockchainsim-data:
    driver: local
